"""
modules/report_generator.py
Generates a comprehensive downloadable Markdown + text report.
"""

import datetime
import pandas as pd

try:
    # When imported as part of the modules package (normal runtime)
    from modules.recommender import recommendations_to_markdown, Recommendation
except ImportError:
    # Relative import fallback (e.g. running from within modules/)
    from recommender import recommendations_to_markdown, Recommendation  # type: ignore


def generate_report(
    df: pd.DataFrame,
    eda_results: dict,
    cleaning_report_md: str,
    recommendations: list[Recommendation],
    ai_summary: str,
    filename: str = "airport_data",
) -> str:
    """
    Build a full Markdown report string for download.
    """
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    summary = eda_results.get("summary", {})

    sections = []

    # ── Header ────────────────────────────────────────────────────────────────
    sections.append(f"""# ✈️ AeroLogix AI — Airport Logistics Report
**Generated:** {now}  
**Dataset:** {filename}  
**Report Version:** 1.0  

---
""")

    # ── Executive Summary ─────────────────────────────────────────────────────
    sections.append(f"""## 📋 Executive Summary

{ai_summary}

---
""")

    # ── KPI Dashboard ─────────────────────────────────────────────────────────
    sections.append(f"""## 📊 Key Performance Indicators

| Metric | Value |
|--------|-------|
| Total Flights Analysed | {summary.get('total_flights', 0):,} |
| Delayed Flights | {summary.get('delayed_flights', 0):,} |
| On-Time Flights | {summary.get('on_time_flights', 0):,} |
| **Delay Rate** | **{summary.get('delay_rate_pct', 0):.1f}%** |
| Avg Delay (delayed flights) | {summary.get('avg_delay_minutes', 0):.0f} min |
| Maximum Delay | {summary.get('max_delay_minutes', 0):.0f} min |
| Total Cargo Handled | {summary.get('total_cargo_kg', 0):,.0f} kg |
| Total Baggage Pieces | {summary.get('total_baggage_pieces', 0):,} |
| Airlines Operating | {summary.get('airlines_count', 0)} |
| Gates Utilised | {summary.get('gates_used', 0)} |

---
""")

    # ── Data Cleaning ─────────────────────────────────────────────────────────
    sections.append(cleaning_report_md + "\n\n---\n")

    # ── Delay Analysis ────────────────────────────────────────────────────────
    delay_df: pd.DataFrame = eda_results.get("delay_by_airline", pd.DataFrame())
    if not delay_df.empty:
        sections.append("## ✈️ Delay Analysis by Airline\n")
        sections.append(_df_to_md(delay_df) + "\n\n---\n")

    # ── Gate Congestion ───────────────────────────────────────────────────────
    gate_df: pd.DataFrame = eda_results.get("gate_congestion", pd.DataFrame())
    if not gate_df.empty:
        sections.append("## 🚦 Gate Congestion Analysis\n")
        sections.append(_df_to_md(gate_df.head(10)) + "\n\n---\n")

    # ── Cargo Analysis ────────────────────────────────────────────────────────
    cargo_df: pd.DataFrame = eda_results.get("cargo", pd.DataFrame())
    if not cargo_df.empty:
        sections.append("## 📦 Cargo & Baggage Analysis\n")
        sections.append(_df_to_md(cargo_df) + "\n\n---\n")

    # ── Top Routes ────────────────────────────────────────────────────────────
    routes_df: pd.DataFrame = eda_results.get("top_routes", pd.DataFrame())
    if not routes_df.empty:
        sections.append("## 🗺️ Top Routes\n")
        sections.append(_df_to_md(routes_df) + "\n\n---\n")

    # ── Recommendations ───────────────────────────────────────────────────────
    sections.append(recommendations_to_markdown(recommendations))
    sections.append("\n---\n")

    # ── Footer ────────────────────────────────────────────────────────────────
    sections.append(f"""## 📝 Report Notes

- This report was generated automatically by AeroLogix AI.
- All delay statistics reflect the uploaded dataset only.
- Recommendations are data-driven suggestions and should be validated with operations teams.
- For questions, use the AI Q&A panel in the AeroLogix dashboard.

*Report generated by AeroLogix AI — Airport Logistics Analytics & Optimization Agent*  
*Powered by LangChain + Groq/Gemini | {now}*
""")

    return "\n".join(sections)


def _df_to_md(df: pd.DataFrame) -> str:
    """Convert a DataFrame to a Markdown table."""
    if df.empty:
        return "_No data available._"
    header = "| " + " | ".join(str(c) for c in df.columns) + " |"
    sep = "| " + " | ".join(["---"] * len(df.columns)) + " |"
    rows = []
    for _, row in df.iterrows():
        cells = []
        for v in row.values:
            if isinstance(v, bool):
                cells.append(str(v))
            elif isinstance(v, float):
                cells.append(f"{v:,.1f}")
            elif isinstance(v, int):
                cells.append(f"{v:,}")
            else:
                cells.append(str(v))
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([header, sep] + rows)